'use strict';
// Persistent level IDs are independent of room IDs and the ten-floor campaign.
const ExpeditionLevels = (() => {
  const rooms = [
    ['Лунная пристань','crescent','moonwell','moonpillar'],
    ['Сад серебряного плюща','garden','moonpillar','crystal'],
    ['Двор небесных часов','orrery','astrolabe','moonwall'],
    ['Архив утраченных имён','archive','starbooks','moonpillar'],
    ['Расколотый планетарий','crescent','astrolabe','crystal'],
    ['Хранилище звёздных карт','archive','starbooks','moonwall'],
    ['Страж зеркальной воды','terrace','moonwell','moonpillar'],
    ['Купель тишины','garden','moonwell','crystal'],
    ['Галерея созвездий','archive','starbooks','moonpillar'],
    ['Перекрёсток комет','orrery','astrolabe','crystal'],
    ['Тайник лунного стекла','crescent','crystal','starbooks'],
    ['Сад расколотых лун','garden','moonpillar','crystal'],
    ['Палата падающих звёзд','terrace','crystal','moonwall'],
    ['Караул последнего света','archive','starbooks','moonpillar'],
    ['Родник перед затмением','crescent','moonwell','moonwall'],
    ['Обсерватория затмения','observatory','astrolabe','moonpillar'],
  ].map(([name,shape,landmark,propStyle])=>Object.freeze({biome:'eclipse',name,shape,landmark,propStyle}));
  const rootRooms=[
    ['Пристань красных листьев','crescent','bloodtree','rootpillar'],
    ['Грибные ступени','fungal','fungi','bloodtree'],
    ['Двор первого звона','belfry','bellframe','rootpillar'],
    ['Терновый дозор','cruciform','rootpillar','roothedge'],
    ['Сад пустых коконов','grove','bloodtree','fungi'],
    ['Тайник под чашелистником','fungal','fungi','roothedge'],
    ['Расколотая колокольня','belfry','bellframe','rootpillar'],
    ['Зеркало тихой воды','crescent','rootpool','bloodtree'],
    ['Аллея багряных масок','grove','rootpillar','bloodtree'],
    ['Переплетение корней','cruciform','bloodtree','roothedge'],
    ['Схрон янтарной смолы','terrace','fungi','rootpillar'],
    ['Палата спор','fungal','fungi','roothedge'],
    ['Сад оброненных крыльев','grove','bloodtree','fungi'],
    ['Зал Слепого звонаря','belfry','bellframe','rootpillar'],
    ['Купель последнего семени','crescent','rootpool','rootpillar'],
    ['Сердце Багряного корнесвода','heartwood','bloodtree','bellframe'],
  ].map(([name,shape,landmark,propStyle])=>Object.freeze({biome:'rootvault',name,shape,landmark,propStyle}));
  const stormRooms=[
    ['Пристань белого пепла','crescent','frostpillar','icecluster'],
    ['Двор солнечных щитов','sunwheel','frostpillar','frostwall'],
    ['Развилка ледяных арок','cruciform','frostpillar','icecluster'],
    ['Караул сломанного шпиля','rampart','frostpillar','frostwall'],
    ['Сады ледяного стекла','icegarden','icecluster','frostpillar'],
    ['Кузница последнего огня','rampart','frostpillar','frostwall'],
    ['Западный маяк бури','sunwheel','frostpillar','icecluster'],
    ['Тёплый родник под снегом','crescent','icecluster','frostpillar'],
    ['Галерея семи ветров','rampart','frostpillar','frostwall'],
    ['Площадь расколотого солнца','sunwheel','frostpillar','icecluster'],
    ['Зал картографов','archive','frostpillar','frostwall'],
    ['Балкон северного ветра','terrace','icecluster','frostpillar'],
    ['Восточный маяк бури','sunwheel','frostpillar','icecluster'],
    ['Караул Ледяного венца','rampart','frostpillar','frostwall'],
    ['Привал перед бурей','icegarden','icecluster','frostwall'],
    ['Трон Архонта Бури','stormthrone','frostpillar','icecluster'],
  ].map(([name,shape,landmark,propStyle])=>Object.freeze({biome:'storm',name,shape,landmark,propStyle}));
  const chapterRooms=(biome,rows)=>rows.map(([name,shape,landmark,propStyle])=>Object.freeze({biome,name,shape,landmark,propStyle}));
  const tideRooms=chapterRooms('tide',[
    ['Причал утонувших писем','tidalquay','tidescholar','tidepillar'],
    ['Зал нефритовых волн','tidalhall','tidebasin','tideshelves'],
    ['Развилка под акведуком','cloister','tidepillar','tidewall'],
    ['Караул жемчужной печати','tidalhall','tidescholar','tidepillar'],
    ['Сад затонувших статуй','reservoir','tidescholar','tidewall'],
    ['Архив закрытых свитков','archive','tideshelves','tidepillar'],
    ['Дозор у водяных часов','cloister','tidebasin','tidepillar'],
    ['Купель тихого прилива','reservoir','tidebasin','tidewall'],
    ['Галерея медных переплётов','tidalhall','tideshelves','tidescholar'],
    ['Двор трёх течений','tidalquay','tidepillar','tidewall'],
    ['Тайник соляной летописи','archive','tideshelves','tidewall'],
    ['Палата расколотых раковин','reservoir','tidescholar','tidepillar'],
    ['Перекрёсток отлива','cloister','tidebasin','tidescholar'],
    ['Стража последнего писца','tidalhall','tideshelves','tidepillar'],
    ['Родник безымянного берега','tidalquay','tidebasin','tidewall'],
    ['Апсида Хранителя прилива','tideapse','tidescholar','tidepillar'],
  ]);
  const forgeRooms=chapterRooms('sunforge',[
    ['Причал угольных барж','slagterrace','sunpillar','slagwall'],
    ['Двор железных искр','anvilcourt','sunfurnace','sunpillar'],
    ['Галерея остывших молотов','furnacehall','sunanvil','slagwall'],
    ['Караул огненных масок','anvilcourt','sunpillar','sunfurnace'],
    ['Террасы расплавленной меди','slagterrace','slagbasin','sunpillar'],
    ['Кладовая звёздного железа','furnacehall','sunanvil','slagwall'],
    ['Бастион клеймёных лат','rampart','sunpillar','sunfurnace'],
    ['Привал у холодного горна','slagterrace','sunanvil','slagwall'],
    ['Двор расколотой наковальни','anvilcourt','sunanvil','sunpillar'],
    ['Распутье Чёрного Солнца','solarwheel','sunfurnace','slagwall'],
    ['Тайник медных углей','furnacehall','slagbasin','sunanvil'],
    ['Галерея вечной плавки','slagterrace','sunfurnace','sunpillar'],
    ['Зал погасших созвездий','solarwheel','sunanvil','slagwall'],
    ['Караул последнего закала','anvilcourt','sunpillar','sunfurnace'],
    ['Купель перед затмением','slagterrace','slagbasin','slagwall'],
    ['Горнило Чёрного Солнца','solarcrucible','sunfurnace','sunpillar'],
  ]);
  const amberRooms=chapterRooms('amber',[
['Причал погребальных ладей', 'burialquay', 'amberpillar', 'amberwall'],
['Двор бронзовых венцов', 'burialcourt', 'ambersarcophagus', 'amberpillar'],
['Аллея янтарных корней', 'resingarden', 'ambertree', 'amberwall'],
['Караул медных масок', 'urnhall', 'amberpillar', 'amberpillar'],
['Террасы забытых имён', 'burialquay', 'ambersarcophagus', 'amberwall'],
['Кладовая смоляных печатей', 'urnhall', 'ambertree', 'amberpillar'],
['Дозор погребального солнца', 'burialcourt', 'amberpillar', 'amberwall'],
['Купель тихого ладана', 'resingarden', 'amberbasin', 'amberpillar'],
['Галерея пустых саркофагов', 'urnhall', 'ambertree', 'amberwall'],
['Перекрёсток бронзовых корней', 'resingarden', 'amberpillar', 'amberpillar'],
['Тайник последней династии', 'burialquay', 'ambersarcophagus', 'amberwall'],
['Зал крылатых урн', 'urnhall', 'ambertree', 'amberpillar'],
['Площадь застывшей смолы', 'burialcourt', 'amberpillar', 'amberwall'],
['Стража немого царя', 'burialcourt', 'ambersarcophagus', 'amberpillar'],
['Родник перед венчанием', 'resingarden', 'amberbasin', 'amberwall'],
['Трон Янтарного царя', 'amberthrone', 'amberpillar', 'amberpillar'],
]);
  const glassRooms=chapterRooms('glass',[
['Пристань лунных лепестков', 'petalquay', 'glasspillar', 'glasswall'],
['Двор расколотых отражений', 'mirrorcourt', 'glassmirror', 'glasspillar'],
['Галерея серебряных арок', 'glassgallery', 'glasswillow', 'glasswall'],
['Дозор стеклянных крыльев', 'mirrorcourt', 'glasspillar', 'glasspillar'],
['Сад безмолвных ив', 'willowgarden', 'glassmirror', 'glasswall'],
['Тайник холодного серебра', 'glassgallery', 'glasswillow', 'glasspillar'],
['Караул хрустального свода', 'mirrorcourt', 'glasspillar', 'glasswall'],
['Родник отражённой луны', 'willowgarden', 'glassbasin', 'glasspillar'],
['Террасы серебряного инея', 'petalquay', 'glasswillow', 'glasswall'],
['Площадь трёх отражений', 'mirrorcourt', 'glasspillar', 'glasspillar'],
['Хранилище лунных осколков', 'glassgallery', 'glassmirror', 'glasswall'],
['Галерея замёрзших цветов', 'glassgallery', 'glasswillow', 'glasspillar'],
['Двор потерянных теней', 'petalquay', 'glasspillar', 'glasswall'],
['Стража последней луны', 'mirrorcourt', 'glassmirror', 'glasspillar'],
['Купель белого лепестка', 'willowgarden', 'glassbasin', 'glasswall'],
['Венец Лунного Стекла', 'glasscrown', 'glasspillar', 'glasspillar'],
]);
  const levels = {
    undermountain: {id:'undermountain',name:'Подгорье',floor:1,next:'eclipse',mapLegend:'Корни · Бастион · Горны',bossName:'Хранитель Пепельной Короны'},
    eclipse: {id:'eclipse',name:'Обсерватория затмения',floor:2,next:'rootvault',mapLegend:'Архивы · Лунные сады · Обсерватория',bossName:'Астроном Пустоты',rooms,
      encounters:[['wraith','goblin'],['archer','shadow','goblin'],['spider','wraith','goblin']],
      elite:['uruk','archer','shadow'],boss:['morgul','wraith','shadow'],
      bossDef:{...BOSSES.morgul,name:'Астроном Пустоты',hp:680,dmg:18,armor:2,speed:100,color:'#8574cb',abilities:{blink:8,volley:6,summon:18,scream:13}},
    },
    rootvault:{id:'rootvault',name:'Багряный корнесвод',floor:3,next:'storm',mapLegend:'Грибные сады · Колокольни · Сердце корней',bossName:'Матерь корней',rooms:rootRooms,nativeBosses:true,
      encounters:[['thornstalker','embermoth'],['carapace','sporecantor'],['thornstalker','sporecantor','embermoth']],
      elite:['carapace','thornstalker','embermoth'],boss:['rootmother','thornstalker','sporecantor'],
      roomEncounters:{13:['bellwarden','embermoth']},
    },
    storm:{id:'storm',name:'Цитадель Белой Бури',floor:4,next:'tide',mapLegend:'Маяки ослабляют Архонта · Кузница · Картографы',bossName:'Архонт Бури',rooms:stormRooms,nativeBosses:true,
      notice:'Погасите маяки, чтобы ослабить Архонта, или идите к нему сразу. Карта — M.',
      positions:[[0,3],[1,3],[2,3],[1,2],[3,3],[0,2],[1,1],[3,2],[2,1],[2,0],[4,2],[1,-1],[3,0],[3,-1],[4,0],[4,-1]],
      spacing:[816,560],passageFlare:80,
      edges:[[0,1],[1,2],[1,3],[3,5],[3,6],[2,4],[4,7],[7,10],[6,8],[7,8],[8,9],[9,11],[9,12],[11,13],[12,13],[12,14],[14,15],[13,15],[2,7],[3,8]],
      encounters:[['wraith','archer'],['uruk','wraith'],['archer','shadow','wraith']],elite:['uruk','wraith','shadow'],boss:['stormarchon','wraith','uruk'],
      features:{5:{kind:'forge',sprite:'stormforge',title:'Кузница последнего огня'},10:{kind:'chart',sprite:'charttable',title:'Память картографов'},6:{kind:'beacon',sprite:'stormbeacon',title:'Западный маяк'},12:{kind:'beacon',sprite:'stormbeacon',title:'Восточный маяк'}},
    },
    tide:{id:'tide',name:'Затопленные архивы',floor:5,next:'sunforge',mapLegend:'Пристани · Затонувшие галереи · Хранитель прилива',bossName:'Хранитель прилива',rooms:tideRooms,nativeBosses:true,
      notice:'Затопленные архивы. Вода окружает сухие галереи. Ищите Хранителя прилива.',
      positions:[[0,3],[1,3],[1,2],[2,2],[0,1],[0,2],[1,1],[2,1],[3,2],[3,1],[4,2],[2,0],[3,0],[1,0],[3,-1],[4,-1]],spacing:[816,544],passageFlare:94,
      edges:[[0,1],[1,2],[1,5],[2,5],[5,4],[4,6],[2,6],[6,7],[2,3],[3,8],[8,10],[8,9],[9,7],[7,11],[6,13],[13,11],[11,12],[9,12],[12,14],[14,15],[12,15],[3,7]],
      encounters:[['wraith','archer','shadow'],['carapace','wraith'],['sporecantor','shadow']],elite:['carapace','archer','wraith'],boss:['tidewarden','carapace','wraith'],
    },
    sunforge:{id:'sunforge',name:'Кузня Чёрного Солнца',floor:6,next:'amber',mapLegend:'Наковальни · Литейные дворы · Кузнец затмения',bossName:'Кузнец затмения',rooms:forgeRooms,nativeBosses:true,
      notice:'Кузня Чёрного Солнца. Найдите горнило Кузнеца затмения. Лестница ведёт в Янтарный некрополь.',
      positions:[[0,4],[1,4],[2,4],[1,3],[3,3],[0,3],[0,2],[2,3],[1,2],[2,2],[4,3],[3,1],[2,1],[4,1],[3,0],[4,0]],spacing:[808,536],passageFlare:104,
      edges:[[0,1],[1,2],[1,3],[3,5],[5,6],[6,8],[3,8],[2,7],[7,4],[4,10],[7,9],[8,9],[9,12],[12,11],[11,13],[13,15],[11,14],[14,15],[4,9],[9,11]],
      encounters:[['uruk','embermoth'],['troll','archer'],['thornstalker','embermoth','goblin']],elite:['troll','embermoth','uruk'],boss:['sunforger','uruk','embermoth'],
    },
    amber:{id:'amber',name:'Янтарный некрополь',floor:7,next:'glass',mapLegend:'Саркофаги · Смоляные сады · Янтарный царь',bossName:'Янтарный царь',rooms:amberRooms,nativeBosses:true,
      notice:'Некрополь. Обходите щит Могильного стража; прерывайте заклинания Кадильщика.',
      positions:[[0,4],[1,4],[2,4],[1,3],[3,4],[0,3],[0,2],[2,3],[1,2],[3,3],[4,3],[2,1],[3,2],[1,1],[3,0],[4,1]],spacing:[816,536],passageFlare:110,
      edges:[[0,1],[1,2],[1,3],[3,5],[5,6],[6,8],[8,3],[2,4],[4,9],[9,10],[2,7],[7,3],[7,9],[7,8],[8,13],[13,11],[11,12],[12,9],[11,14],[12,14],[14,15],[12,15]],
      encounters:[['tombguard','censer'],['censer','wraith','goblin'],['tombguard','archer']],elite:['tombguard','censer','wraith'],boss:['amberking','tombguard','censer'],
    },
    glass:{id:'glass',name:'Сады Лунного Стекла',floor:8,next:null,mapLegend:'Зеркальные дворы · Серебряные ивы · Хранительница отражений',bossName:'Хранительница отражений',rooms:glassRooms,nativeBosses:true,
      notice:'Сады Лунного Стекла. Дуэлянты атакуют по прямой, моль стреляет веером. Ищите Хранительницу.',
      positions:[[0,3],[1,3],[2,3],[2,2],[0,1],[0,2],[1,1],[3,2],[3,3],[3,1],[4,2],[1,0],[2,0],[2,1],[3,-1],[4,-1]],spacing:[816,552],passageFlare:118,
      edges:[[0,1],[0,5],[1,2],[1,5],[5,4],[4,6],[6,11],[11,12],[6,13],[13,3],[2,3],[2,8],[8,7],[7,10],[7,9],[9,13],[3,7],[13,12],[12,14],[14,15],[9,14]],
      encounters:[['glassduelist','prismmoth'],['glassduelist','wraith','archer'],['prismmoth','prismmoth','shadow']],elite:['glassduelist','prismmoth','wraith'],boss:['glassregent','glassduelist','prismmoth'],
    },
  };
  for(const level of Object.values(levels))Object.freeze(level);
  return Object.freeze({levels:Object.freeze(levels),get:id=>levels[id]||null});
})();

