(() => {
  'use strict';
  const maps=[
    ['drownedwharf','01','Верфь утонувшего света','Затонувшие корпуса, мокрые настилы и охотники с цепными крюками.','#79b6b8'],
    ['redquarry','02','Красный карьер','Глиняные уступы, керамические жилы и тяжёлые камнерезы.','#e49a73'],
    ['darkroot','03','Сердце тёмного корня','Корневые проходы, споровые засады и древнее семенное сердце.','#b1c28e']
  ].filter(m=>ExpeditionLevels.get(m[0])?.id===m[0]);
  const previous=UI.prototype.showMenu;
  UI.prototype.showMenu=function(){
    const g=this.g;g.state='menu';g.input.keys={};g.input.pressed={};g.input.mouse.down=false;
    const hero=g.v27Hero||g.player?.heroId||'arator',difficulty=g.expeditionDifficulty||'journey';
    this.render(`<div class="v27-launch"><style>
      .v27-launch{position:fixed;inset:0;z-index:20;overflow:auto;pointer-events:auto;background:radial-gradient(ellipse at 25% 0%,#273132,#0d1418 65%);color:#eadfc6;font-family:Georgia,serif;padding:clamp(20px,4vw,58px);box-sizing:border-box;text-align:left}
      .v27-launch *{box-sizing:border-box}.v27-wrap{max-width:1180px;margin:auto}.v27-kicker{font:12px sans-serif;letter-spacing:3px;color:#bca77c}.v27-launch h1{font-size:clamp(30px,4vw,52px);line-height:1.08;margin:14px 0}.v27-lede{color:#a9b3b1;max-width:650px;line-height:1.6}.v27-controls{display:flex;gap:20px;flex-wrap:wrap;margin:24px 0}.v27-controls label{display:grid;gap:8px;font:13px sans-serif}.v27-controls select{padding:12px 16px;background:#1b272b;color:#eadfc6;border:1px solid #4c5b5d;border-radius:6px;min-width:180px}.v27-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.v27-card{display:flex;flex-direction:column;border:1px solid #48514b;border-top:3px solid var(--tone);border-radius:8px;padding:25px;background:linear-gradient(155deg,#283230,#171e21);min-height:282px}.v27-card small{font:12px sans-serif;letter-spacing:2px;color:var(--tone)}.v27-card h2{font-size:25px;line-height:1.1;margin:20px 0 10px}.v27-card p{color:#b5bfba;font:15px/1.6 sans-serif;flex:1}.v27-launch button{font:600 14px sans-serif;cursor:pointer;border:1px solid #677468;padding:13px 18px;border-radius:5px;background:#d9c69a;color:#162224;min-height:46px}.v27-actions{display:flex;gap:8px;flex-wrap:wrap}.v27-launch .v27-secondary{background:transparent;color:#c8d0c6}.v27-foot{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin-top:28px;color:#9baaa6;font:13px/1.6 sans-serif}@media(max-width:740px){.v27-cards{grid-template-columns:1fr}.v27-card{min-height:0}.v27-launch{padding:22px}.v27-card h2{margin:12px 0 4px}}
    </style><div class="v27-wrap"><div class="v27-kicker">ОСКОЛКИ РАССВЕТА · МАСТЕРСКАЯ МИРА</div><h1>Три новых рубежа</h1><p class="v27-lede">Отдельные походы по новым картам. Выберите героя, пройдите комнаты и сразитесь с хранителем в конце пути.</p><div class="v27-controls"><label>Герой<select data-v27-hero>${HEROES.map(h=>`<option value="${h.id}" ${h.id===hero?'selected':''}>${h.name}</option>`).join('')}</select></label><label>Сложность<select data-v27-difficulty>${Object.entries(EncounterDirector.modes).map(([id,m])=>`<option value="${id}" ${id===difficulty?'selected':''}>${m.name}</option>`).join('')}</select></label></div><div class="v27-cards">${maps.map(([id,n,name,desc,tone])=>{let saved=false;try{const s=localStorage.getItem(V27Preview.key(id));saved=!!s&&s!=='null';}catch(_){}return `<article class="v27-card" style="--tone:${tone}"><small>ПОХОД ${n} · 16 КОМНАТ</small><h2>${name}</h2><p>${desc}</p><div class="v27-actions"><button data-v27-start="${id}">Начать поход →</button>${saved?`<button class="v27-secondary" data-v27-resume="${id}">Продолжить</button>`:''}</div></article>`;}).join('')}</div><div class="v27-foot"><button class="v27-secondary" data-v27-campaign>Основная игра</button><span>WASD — движение · мышь — атака · Shift — рывок<br>Способности и управление доступны в паузе. На телефоне — экранные кнопки.</span></div></div></div>`);
    this.bind('[data-v27-hero]','change',el=>{g.v27Hero=el.value;});
    this.bind('[data-v27-difficulty]','change',el=>{g.expeditionDifficulty=el.value;});
    this.bind('[data-v27-start]','click',el=>g.startSeamlessJourney(undefined,g.v27Hero||hero,el.dataset.v27Start,g.expeditionDifficulty||difficulty));
    this.bind('[data-v27-resume]','click',el=>{SeamlessFloor.key=V27Preview.key(el.dataset.v27Resume);if(!g.resumeSeamlessJourney())g.startSeamlessJourney(undefined,g.v27Hero||hero,el.dataset.v27Resume,g.expeditionDifficulty||difficulty);});
    this.bind('[data-v27-campaign]','click',()=>{SeamlessFloor.key=window.V20Storage.key;previous.call(this);});
  };
})();
